In [1]:
import numpy as np

In [2]:
array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)


In [3]:
array2 = np.array([[1,2,3],[2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)


In [4]:
array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [5]:
print('array1:{:0}차원, array2:{:1}차원, array3:{:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1:1차원, array2:2차원, array3: 2차원


In [6]:
list1=[1,2,3]
print(type(list1))
array1=np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [7]:
list2=[1,2,'test']
array2=np.array(list2)
print(array2, array2.dtype)

['1' '2' 'test'] <U11


In [9]:
list3=[1,2,3.0]
array3=np.array(list3)
print(array3, array3.dtype)

[1. 2. 3.] float64


In [10]:
array_int=np.array([1,2,3])
array_float=array_int.astype('float64')
print(array_float, array_float.dtype)

[1. 2. 3.] float64


In [11]:
array_int1=array_float.astype('int32')
print(array_int1, array_int1.dtype)

[1 2 3] int32


In [12]:
array_float1=np.array([1.1,2.1,3.1])
array_int2=array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1 2 3] int32


In [13]:
sequence_array=np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [14]:
zero_array=np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [16]:
one_array=np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [17]:
array1=np.arange(10)
print('array1:\n', array1)

array:1
 [0 1 2 3 4 5 6 7 8 9]


In [18]:
array2=array1.reshape(2,5)
print('array2:\n', array2)

array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [19]:
array3=array1.reshape(5,2)
print('array3:\n', array3)

array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [20]:
array1=np.arange(10)
print(array1)
array2=array1.reshape(-1,5)
print('array2 shape:', array2.shape)
array3=array1.reshape(5,-1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [22]:
array1=np.arange(1,9)
array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())

array3d:
 [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]


In [23]:
array5 = array3d.reshape(-1,1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

array5:
 [[1], [2], [3], [4], [5], [6], [7], [8]]
array5 shape: (8, 1)


In [24]:
array6=array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array6:
 [[1], [2], [3], [4], [5], [6], [7], [8]]
array6 shape: (8, 1)


In [25]:
array1=np.arange(start=1, stop=10)
print('array1:', array1)
value=array1[2]
print('value:', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>


In [26]:
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두번째 값:', array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두번째 값: 8


In [27]:
array1[0]=9
array1[8]=0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


In [28]:
array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3,3)
print(array2d)

print(array2d[0,0])
print(array2d[0,1])
print(array2d[1,0])
print(array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
2
4
9


In [29]:
array1=np.arange(1,10)
array3=array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [30]:
array1=np.arange(1,10)
array4=array1[:3]
print(array4)

array5=array1[3:]
print(array5)

array6=array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [31]:
array1d=np.arange(1,10)
array2d=array1d.reshape(3,3)
print('array2d:\n', array2d)

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [32]:
array1d=np.arange(1,10)
array2d=array1d.reshape(3,3)
array3 = array2d[[0,1],2]
print(array3.tolist())
array4=array2d[[0,1],0:2]
print(array4.tolist())
array5=array2d[[0,1]]
print(array5.tolist())

[3, 6]
[[1, 2], [4, 5]]
[[1, 2, 3], [4, 5, 6]]


In [33]:
array1d=np.arange(start=1, stop=10)
array3=array1d[array1d>5]
print(array3)
print(array1d>5)

[6 7 8 9]
[False False False False False  True  True  True  True]


In [34]:
boolean_indexes=np.array([False, False, False, False, False,  True,  True,  True,  True])
array3=array1d[boolean_indexes]
print(array3)

[6 7 8 9]


In [35]:
indexes=np.array([5,6,7,8])
array4=array1d[indexes]
print(array4)

[6 7 8 9]


In [37]:
org_array=np.array([3,1,9,5])
print(org_array)
sort_array1=np.sort(org_array)
print(sort_array1)
print(org_array)

[3 1 9 5]
[1 3 5 9]
[3 1 9 5]


In [38]:
sort_array2=org_array.sort()
print(sort_array2)
print(org_array)

None
[1 3 5 9]


In [40]:
sort_array1_desc=np.sort(org_array)[::-1]
print(sort_array1_desc)

[9 5 3 1]


In [41]:
array2d=np.array([[8,12],[7,1]])
sort_array2d_axis0 = np.sort(array2d, axis=0)
sort_array2d_axis1 = np.sort(array2d, axis=1)
print(sort_array2d_axis0)
print(sort_array2d_axis1)

[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]


In [42]:
org_array=np.array([3,1,9,5])
sort_indices=np.argsort(org_array)
print(type(sort_indices))
print(sort_indices)

<class 'numpy.ndarray'>
[1 0 3 2]


In [43]:
name_array=np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array=np.array([78,95,84,98,88])

sort_indices_asc=np.argsort(score_array)
print(sort_indices_asc)
print(name_array[sort_indices_asc])

[0 2 4 1 3]
['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


In [44]:
A=np.array([[1,2],[3,4]])
transpose_mat=np.transpose(A)
print(transpose_mat)

[[1 3]
 [2 4]]
